config:
subcomponents:
  elasticsearch:
    config:
      namespace: elasticsearch
      client:
        resources:
          limits:
            memory: "2048Mi"
  elasticsearch-curator:
    config:
      namespace: elasticsearch
      cronjob:
        successfulJobsHistoryLimit: 0
      configMaps:
        config_yml: |-
          ---
          client:
            hosts:
              - elasticsearch-client.elasticsearch.svc.cluster.local
            port: 9200
            use_ssl: False
  fluentd-elasticsearch:
    config:
      namespace: fluentd
      elasticsearch:
        host: "elasticsearch-client.elasticsearch.svc.cluster.local"
  kibana:
    config:
      namespace: kibana
      files:
        kibana.yml:
          elasticsearch.url: "http://elasticsearch-client.elasticsearch.svc.cluster.local:9200"
